name: "Security Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

env:
  ACT: false

jobs:
  gosec:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.22.1
        with:
          # Generates a SARIF file for GitHub Security integration
          args: '-fmt sarif -out results.sarif -exclude=G103,G115 -exclude-dir=test ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        if: ${{ !env.ACT }}
        with:
          sarif_file: results.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
